### ISSUE TITLE
container.addDynamicProperty is not a function

### ISSUE THREAD

**Issue by ShmilyLin** [landn172/lottie-miniapp#14]
**bug描述**
```error
VM586:1 thirdScriptError
container.addDynamicProperty is not a function;at "pages/home/home/home" page lifeCycleMethod onLoad function
TypeError: container.addDynamicProperty is not a function
    at PropertyFactory.GetProp.descriptor.value (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:7345:17)
    at new SliderEffect (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:8201:30)
    at GroupEffect.init (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:8260:15)
    at new GroupEffect (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:8233:8)
    at new EffectsManager (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:8226:18)
    at CVShapeElement.initBaseData (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:9491:29)
    at CVShapeElement.initElement (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:12431:12)
    at new CVShapeElement (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:12423:11)
    at CVCompElement.createShape (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:14829:14)
    at CVCompElement.createItem (http://127.0.0.1:26859/appservice/js/lottie/lottie-miniapp.js:868:23)
```

**复现过程**
```js
// onload
var context = wx.createCanvasContext('home-canvas');//还记得 在wxml里面canvas的id叫first吗
    context.canvas = {
      width: app.systemInfo.windowWidth,
      height: app.systemInfo.windowHeight
    };

    lottie.loadAnimation({
      renderer: 'canvas', // 只支持canvas
      loop: true,
      autoplay: true,
      animationData: NormalAnimationData,
      rendererSettings: {
        context: context,
        clearCanvas: true
      }
    });
```

**期望**

**截图**

**错误设备信息**
 - Device: 模拟器调试

**Comment by landn172** [comment]
@ShmilyLin 请提供 **NormalAnimationData**
