### ISSUE TITLE
微信小程序测试后报错

### ISSUE THREAD

**Issue by cb0207** [landn172/lottie-miniapp#54]
我就按照npm构建，然后使用下面的wxml引用lottie组件。
<lottie width='300' height='300' path='https://assets5.lottiefiles.com/datafiles/e8edab32a32a8a9402f9cd63b457993c/Plane.json'/>
后面就一连串报错, 想上传图片但是一直不成功。所以只好贴上报错码，先谢谢了！

VM309:1 appServiceSDKScriptError
Cannot read property '__wxWebviewId__' of undefined; at wx.createIntersectionObserver
TypeError: Cannot read property '__wxWebviewId__' of undefined
    at new r (WAService.js:1:740368)
    at xl (WAService.js:1:741534)
    at Object.createIntersectionObserver (WAService.js:1:1022381)
    at Object.<anonymous> (WAService.js:1:409592)
    at Object.<anonymous> (WAService.js:1:1027729)
    at Function.<anonymous> (WAService.js:1:1027859)
    at Object.createIntersectionObserver (WAService.js:1:395616)
    at e.value (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/index.js:4204:21)
    at t.value (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/index.js:4342:74)
    at ye.init (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/component/lottie.js:57:37)
console.error @ VM309:1
errorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
value @ index.js:1
value @ index.js:1
init @ lottie.js:55
observer @ lottie.js:22
r.safeCallback @ WAService.js:1
(anonymous) @ WAService.js:1
i.doUpdates @ WAService.js:1
a @ WAService.js:1
e @ WAService.js:1
e @ WAService.js:1
value @ WAService.js:1
x._advancedCreate @ WAService.js:1
x.create @ WAService.js:1
(anonymous) @ WAService.js:1
Fe @ WAService.js:1
value @ WAService.js:1
Ct @ WAService.js:1
(anonymous) @ WAService.js:1
At @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
n @ appservice?t=1564318487026:1555
(anonymous) @ appservice?t=1564318487026:1555
(anonymous) @ appservice?t=1564318487026:1555
_ws.onmessage @ appservice?t=1564318487026:1555
Show 3 more frames
VM309:1 thirdScriptError
Cannot read property 'relativeToViewport' of undefined; [Component] Property Observer Error @ miniprogram_npm/lottie-miniapp/component/lottie#observer
TypeError: Cannot read property 'relativeToViewport' of undefined
    at e.value (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/index.js:4204:71)
    at t.value (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/index.js:4342:74)
    at ye.init (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/component/lottie.js:57:37)
    at ye.observer (http://127.0.0.1:47614/appservice/miniprogram_npm/lottie-miniapp/component/lottie.js:24:14)
    at Function.r.safeCallback (WAService.js:1:1035130)
    at n.<anonymous> (WAService.js:1:1125929)
    at i.doUpdates (WAService.js:1:1141065)
    at a (WAService.js:1:1196183)
    at e (WAService.js:1:1178098)
    at e (WAService.js:1:1178229)

**Comment by cb0207** [comment]
<lottie width='300' height='300' path='https://assets5.lottiefiles.com/datafiles/e8edab32a32a8a9402f9cd63b457993c/Plane.json'/>

**Comment by cb0207** [comment]
我。。一直写着这段代码，上不去
“<lottie width='300' height='300' path='https://assets5.lottiefiles.com/datafiles/e8edab32a32a8a9402f9cd63b457993c/Plane.json'/>”

**Comment by cb0207** [comment]
代码一直上不去，其实是使用组件形式用下面url对path进行赋值。
https://assets5.lottiefiles.com/datafiles/e8edab32a32a8a9402f9cd63b457993c/Plane.json

然后就报错上面的内容。

后面我直接用json数据拷贝进代码，是可以看到效果的。所以是url的问题？

**Comment by landn172** [comment]
看问题是用到了 createIntersectionObserver没有relativeToViewport方法导致报错，尝试把基础库版本升级到较高的版本

**Comment by landn172** [comment]
@cb0207 已修复升级lottie-miniapp@1.8.1
