### ISSUE TITLE
通过wepy组件引入报错

### ISSUE THREAD

**Issue by ChangerHe** [landn172/lottie-miniapp#9]
如题, 按照作者的说法通过wepy引入方式提示如下错误

```
Cannot read property 'length' of undefined;at pages/payBill/index page lifeCycleMethod onShow function
TypeError: Cannot read property 'length' of undefined
    at s.value (http://127.0.0.1:29877/appservice/utils/lottie-miniapp.min.js:3861:468)
    at e.value (http://127.0.0.1:29877/appservice/utils/lottie-miniapp.min.js:4102:141)
    at e.value (http://127.0.0.1:29877/appservice/utils/lottie-miniapp.min.js:4075:628)
    at t.value (http://127.0.0.1:29877/appservice/utils/lottie-miniapp.min.js:4212:74)
    at _class.onShow (http://127.0.0.1:29877/appservice/pages/payBill/index.js:123:34)
    at http://127.0.0.1:29877/appservice/npm/wepy/lib/base.js:193:48
    at Array.forEach (<anonymous>)
    at t.exports.default.$createPage.config.onShow (http://127.0.0.1:29877/appservice/npm/wepy/lib/base.js:192:43)
    at t.<anonymous> (http://127.0.0.1:29877/appservice/__dev__/WAService.js:19:31844)
    at Xt (http://127.0.0.1:29877/appservice/__dev__/WAService.js:20:17023)
```

**Comment by ChangerHe** [comment]
仓库下的demo也无法运行

**Comment by ChangerHe** [comment]
wepy 版本为1.7.2   lottie-miniapp 版本为1.3.2

**Comment by landn172** [comment]
@ChangerHe 我试了下没问题
https://github.com/landn172/lottie-miniapp/tree/fix/wepy 

>  [wepy-example]目录

应该是你的animate.json可能有问题
